exclude: 'build|docs|node_modules|.git|.tox|dist|docs|octue.egg-info|twined.egg-info'
default_stages: [commit]
fail_fast: true
default_language_version:
  python: python3  # force all unspecified python hooks to run python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10240']

  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: ['--line-length', '120']
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - 'pep8-naming'
        args:
          - --ignore-names=setUp,tearDown,setUpClass,tearDownClass,asyncSetUp,asyncTearDown,setUpTestData,failureException,longMessage,maxDiff,startTestRun,stopTestRun

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    - id: pydocstyle

  - repo: https://github.com/thclark/pre-commit-sphinx
    rev: 0.0.1
    hooks:
      - id: build-docs
        language_version: python3
        additional_dependencies:
          - 'Sphinx>=2,<3'
          - 'sphinx-rtd-theme==0.5.0'
          - 'sphinx-tabs==1.2.1'
          - 'sphinx-charts==0.0.4'
          - 'scipy~=1.5.2'
          - 'jsonschema~=3.2.0'

  - repo: https://github.com/windpioneers/pre-commit-hooks
    rev: 0.0.5
    hooks:
      - id: check-branch-name
        args:
          - '^main$'
          - '^development$'
          - '^devops/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^doc/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^feature/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^fix/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^hotfix/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^refactor/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^review/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^enhancement/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'

  - repo: https://github.com/octue/pre-commit-hooks
    rev: 0.5.0
    hooks:
      - id: check-commit-message-is-conventional
        stages: [commit-msg]
