name: Check release branch version against setup.py

on: [push]

jobs:
  check-version-consistency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python .github/workflows/scripts/check-version-consistency.py
