name: Release the package on merge into main

# This workflow will only be triggered when a pull request into main branch is merged (and not closed without merging).
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run-tests:
    if: "github.event.pull_request.merged == true"
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.9'
    strategy:
      matrix:
        python: ['3.8', '3.9']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1

      - name: Get package version
        run: echo "PACKAGE_VERSION=$(poetry version -s)" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own.
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false

  publish:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1

      - name: Build a binary wheel and a source tarball
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
